name: update-snapshots
on:
  # will send emails to last editor of this cron syntax (distroless-bot)
  schedule:
    - cron:  '30 20 * * *'
  workflow_dispatch:
  
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh

    - name: Run update sboms script
      run: |
        for i in $(seq 5); do
          bazel --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc fetch //private/pkg/test/oci_image:test_sboms && break || sleep 20;
        done
        bazel run @//private/pkg/test/oci_image:test_sboms
        echo "Test" >> README.md
        
    - name: Create commits
      run: |
        # Set identity.
        git config --global user.email "distroless-bot@google.com"
        git config --global user.name "Distroless Bot"
        git checkout -b update-snapshots
        # Commit changes
        git add .
        git commit -s -m "Bumping packages to latest stable versions"
        git push origin HEAD
        
    - name: Create Pull Request
      run:
        GH_TOKEN=${{ secrets.ACTIONS_TOKEN }} gh pr create -B main -H update-snapshots -t "Bumping packages to latest stable versions" -b "Bumping packages to latest stable versions" 
